### PR TITLE
Test on my fork: Allow to clone and monitor a job when creating a PR

### PR DESCRIPTION
**Pull request by Martchus**
Test PR 2

@openqa: Clone https://openqa.opensuse.org/tests/3957590

---

### CODE REVIEW

**Comment by foursixnine** [comment]
@openqa Clone https://openqa.opensuse.org/tests/39

**Comment by foursixnine** [comment]
@openqa Clone https://openqa.suse.de/tests/13343733

**Comment by Martchus** [comment]
That won't work as we declared parsing comments as out of scope for now (https://progress.opensuse.org/issues/130934#Out-of-scope).

**Comment by foursixnine** [comment]
> That won't work as we declared parsing comments as out of scope for now (https://progress.opensuse.org/issues/130934#Out-of-scope).

A man can dream :)

**Comment by Martchus** [comment]
openqa: Clone https://openqa.opensuse.org/tests/4188055

**Pull request closed without merging**
